### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by johannaspo** [ereborinkorppi/torihinnat#1]
Sovelluksen pohja näyttää olevan jo hyvällä mallilla, hyvä! Tässä muutamia huomioita:
- Tuotteen hinta voi olla negatiivinen
- Jos yrittää lisätä tuotetta ilman, että valitsee toisen radiobuttoneista, tulee bad request (toinen siis kannattaa olla valittuna defaultina)
- Myyntipaikan voi lisätä puutteellisilla tiedoilla (eli ilman osoitetta yms)
- Jos yrittää lisätä tuotteita muokkaa tuotteita -kohdasta, tulee internal server error
- Tuotteiden/myyntipaikkojen poistaminen voisi olla käyttäjäystävällisempää tuotteen tai paikan viereen laitetulla poista-napilla
- Lisätty-päivämäärässä ei luultavasti tarvita ainakaan minuutteja pienempiä aikayksiköitä
- routes.py:ssä on joitain tietokantahakuja, jotka voisi siirtää toiseen tiedostoon

**Comment by ereborinkorppi** [comment]
Kiitos hyvästä palautteesta, oli mukava kehittää sovellusta tämäkin tukena.
