### ISSUE TITLE
Vertaisarvio 2

### ISSUE THREAD

**Issue by mrgrotell** [ereborinkorppi/torihinnat#2]
- Lomakkeissa tulisi olla **minimi ja maksimipituudet**. Nyt on mahdollista lähettää tyhjää tietoa ja todella pitkää.
- Olisi hyvä jos hinnoilla olisi looginen **minimi ja maksimiarvo**.
- Tulisi tarkastaa, että käyttäjä on kirjautunut sisään voidakseen kirjautua ulos. Nyt jos kirjaudutaan ulos ilman sisäänkirjautumista tapahtuu **internal server error**.
- **404 not found** voisi indikoida paremmin. Esimerkiksi "Sivua ei löydy."
- Salasanalla tulisi olla minimipituus.
- **/admin** sivulle pääsee ilmeisesti ilman admin oikeuksia. Siellä ei tosin näy mitään mutta sen voisi indikoida esimerkiksi "Pääsy estetty tms."
- Kirjautumiseen ja rekisteröitymiseen pääsee vaikka olisi jo kirjautunut sisälle.
- Sivuston lomakkeet ovat haavoittuvaisia **crfs** hyökkäykselle.
- Kohta jossa lisätään uusi hinta ja valitaan litra tai kilohinta radiobuttonin arvoa voi muokata ja näin palvelimelle voi lähettää mitä tietoa haluaa. Jos esimerkiksi €/litra tilalle laittaa pitkän tiedon sivun leveys venyy todella isoksi.
- Kun lisätään uusi hintatieto käyttäjä voi muuttaa select boksin idtä jolloin pystyy valitsemaan tuotteen mikä ei olisi normaalisti näkyvissä. (**Marja**) kuva 2 ja 3. Jos asettaa idn jota ei ole olemassa aiheutuu **internal server error**. Sama koskee myös myyntipaikan valintaa. Jos idtä muokkaa niin kaupungiksi tulee **None**
- Uuden myyntipaikan lisäämiseen voisi lisätä validaattorin postinumerolle.

![Screenshot 2020-11-30 at 16 57 46](https://user-images.githubusercontent.com/58728411/100625442-358e5f80-332d-11eb-961b-c8124e39ccfd.png)
![Screenshot 2020-12-01 at 16 11 45](https://user-images.githubusercontent.com/58728411/100751823-7f8c4980-33f0-11eb-8ab2-523e2f2dba0f.png)
![Screenshot 2020-12-01 at 16 11 54](https://user-images.githubusercontent.com/58728411/100751826-8024e000-33f0-11eb-83c5-03fe8081ca31.png)

**Comment by ereborinkorppi** [comment]
Kiitos kattavasta testauksesta ja palautteesta. Tämän pohjalta on hyvä kehittää jällleen eteenpäin tätä sovellusta ja omaa osaamista. Monta asiaa sainkin jo taas korjattua näiden huomioiden pohjalta.
